### ISSUE TITLE
maven中央仓库找不到构件

### ISSUE THREAD

**Issue by wangran99** [lunasaw/gb28181-proxy#10]
![image](https://github.com/lunasaw/gb28181-proxy/assets/17898332/4dd4e95a-9251-4491-a86a-06fe6f385ee2)

**Comment by wangran99** [comment]
阿里云里边也没有，版本1.0.7

**Comment by lunasaw** [comment]
目前还是先遣包，可能deploy不是很及时。建议是先拉下来本地install

**Comment by wangran99** [comment]
1.1.0版本已经能够在仓库中下载。
