### ISSUE TITLE
GBSipDevice注册失败

### ISSUE THREAD

**Issue by wangran99** [lunasaw/gb28181-proxy#20]
proxy server版本：1.1.3

客户端：
![image](https://github.com/lunasaw/gb28181-proxy/assets/17898332/7502fe2c-5010-401c-9228-fa64548be2bc)

报错信息：
![image](https://github.com/lunasaw/gb28181-proxy/assets/17898332/fcca802b-ea5c-4801-9166-0f0a90a3cad7)

GBSipDevice模拟设备下载地址：[https://github.com/QuickGBLink88/GB28181_ServerPlatform](https://github.com/QuickGBLink88/GB28181_ServerPlatform)

**Comment by wangran99** [comment]
![image](https://github.com/lunasaw/gb28181-proxy/assets/17898332/d009e8d5-4f09-431b-829d-6ee037373254)

另外，request对象的ip地址都带着/前缀，是否没有影响

**Comment by lunasaw** [comment]
REGISTER sip:41010500002000000001@4101050000 SIP/2.0
Via: SIP/2.0/TCP 172.19.14.30:53911;rport=53911;branch=z9hG4bK51468355;received=172.19.14.30
From: <sip:34020000001320000001@4101050000>;tag=1507709411
To: <sip:34020000001320000001@4101050000>
Call-ID: 803458076
CSeq: 1 REGISTER
Contact: <sip:34020000001320000001@172.19.14.30:5060>
Max-Forwards: 70
User-Agent: IP Camera
Expires: 3600
Content-Length: 0

我还海康注册正常这个是直接拿的sip的url头，一个sipUrl 是 sip:41010500002000000001@4101050000 SIP/2.0 这样的，可以直接拿到userId的，可以也可以改成从header取
  public static String getUser(Request request) {
        return ((SipUri) request.getRequestURI()).getUser();
    }

**Comment by lunasaw** [comment]
![image](https://github.com/lunasaw/gb28181-proxy/assets/52351139/13757879-3b17-4684-ac29-0ae1ef3de99a)
这个client发送的sipurl不能获取到sipid，可以考虑去掉这个校验。

**Comment by wangran99** [comment]
好的，感谢
